### ISSUE TITLE
Comma after last item

### ISSUE THREAD

**Issue by reneklacan** [reevoo/reevoocop#1]
Current configuration consider use of comma after last element as a offense.

I propose that we should be adding comma after last element.

Reasons I see to do so:
- More error proof - usually when I am adding new element to the end of the list I forget about putting comma
- More precise git history & diffs as line with added comma behaves as changed

What do you think?

**Comment by lpil** [comment]
I write without a trailing comma, though I don't have overly strong feelings either way.

We can enforce a trailing comma with rubocop like this.

``` yaml
TrailingComma:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStyles:
    - comma
    - no_comma
```
